### ISSUE TITLE
!r should give /ws guns and knife

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#17]
Using /r on course doesn't reset your pistol from /ws, and doesn't allow a player to change their knife. Simple fix would be to make /r kill and respawn the player, or to just give the gun.

**Comment by hlstriker** [comment]
I would not change !r to respawn the player. It teleports to the first stage on purpose since there are many maps where the spawn is pretty far from the first stage. The correct fix would be to reapply weapons in the weapon plugin when the player uses the !r command.

There is already a forward available for when the !r command is used:
https://github.com/hlstriker/SMPlugins/blob/master/Mods/SpeedRuns/Includes/speed_runs_teleport.inc#L23

**Comment by hlstriker** [comment]
After thinking more on this I remembered the reason I didn't allow replacing the knife without a respawn was because it wouldn't give the player their actual knife model/skin if they had one (unless CS:GO will automatically replace those knives with the player's skin version, but I don't think so).

https://github.com/hlstriker/SMPlugins/blob/master/Plugins/SkillServerWeapons/SkillServerWeapons.sp#L411

When I remake the real !ws plugin I'll hook it into the skill server weapon plugin, then the restriction can be lifted if the real !ws plugin is active.
